authorName: default
experimentName: pytorch_cifar10
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Curvefitting
  classArgs:
    epoch_num: 50
    threshold: 0.95
trial:
  command: python3 trails.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu:  1